static const char *console_js =
    "var console = { log: print, error: print, warning: print, info: print };\n"
;

static const char *graphics_js =
    "var graphics = {\n"
        "drawRectangle: Hate_Graphics_DrawRectangle,\n"
        "drawText: Hate_Graphics_DrawText,\n"
        "measureText: Hate_Graphics_MeasureText,\n"
    "};\n"
;

static const char *input_js =
    "var input = {\n"
        "isKeyPressed: Hate_Input_IsKeyPressed,\n"
        "isKeyDown: Hate_Input_IsKeyDown,\n"
        "isKeyUp: Hate_Input_IsKeyUp\n"
    "};\n"
;

static const char *collision_js =
    "var collision = {\n"
        "checkRecs: Hate_Collision_CheckRecs,\n"
        "getCollisionRec: Hate_Collision_GetCollisionRec\n"
    "};\n"
;

static const char *require_js =
    "var exports = {};\n"
    "function require(name) {\n"
        "var cache = require.cache;\n"
        "if (name in cache) return cache[name];\n"
        "var exports = {};\n"
        "cache[name] = exports;\n"
        "Function('exports', read(name+'.js'))(exports);\n"
        "return exports;\n"
    "}\n"
    "require.cache = Object.create(null);\n"
;

static const char *stacktrace_js =
	"Error.prototype.toString = function() {\n"
        "var s = this.name;\n"
        "if ('message' in this) s += ': ' + this.message;\n"
        "if ('stack' in this) s += this.stack;\n"
        "return s;\n"
	"};\n"
;

static const char *raylib_enums_js =
    "var ConfigFlags = {\n"
        "VsyncHint: 64,\n"
        "FullscreenMode: 2,\n"
        "WindowResizable: 4,\n"
        "WindowUndecorated: 8,\n"
        "WindowHidden: 128,\n"
        "WindowMinimized: 512,\n"
        "WindowMaximized: 1024,\n"
        "WindowUnfocused: 2048,\n"
        "WindowTopmost: 4096,\n"
        "WindowAlwaysRun: 256,\n"
        "WindowTransparent: 16,\n"
        "WindowHighdpi: 8192,\n"
        "WindowMousePassthrough: 16384,\n"
        "BorderlessWindowedMode: 32768,\n"
        "Msaa4xHint: 32,\n"
        "InterlacedHint: 65536\n"
    "};\n"
    "var TraceLogLevel = {\n"
        "All: 0,\n"
        "Trace: 1,\n"
        "Debug: 2,\n"
        "Info: 3,\n"
        "Warning: 4,\n"
        "Error: 5,\n"
        "Fatal: 6,\n"
        "None: 7\n"
    "};\n"
    "var KeyboardKey = {\n"
        "Null: 0,\n"
        "Apostrophe: 39,\n"
        "Comma: 44,\n"
        "Minus: 45,\n"
        "Period: 46,\n"
        "Slash: 47,\n"
        "Zero: 48,\n"
        "One: 49,\n"
        "Two: 50,\n"
        "Three: 51,\n"
        "Four: 52,\n"
        "Five: 53,\n"
        "Six: 54,\n"
        "Seven: 55,\n"
        "Eight: 56,\n"
        "Nine: 57,\n"
        "Semicolon: 59,\n"
        "Equal: 61,\n"
        "A: 65,\n"
        "B: 66,\n"
        "C: 67,\n"
        "D: 68,\n"
        "E: 69,\n"
        "F: 70,\n"
        "G: 71,\n"
        "H: 72,\n"
        "I: 73,\n"
        "J: 74,\n"
        "K: 75,\n"
        "L: 76,\n"
        "M: 77,\n"
        "N: 78,\n"
        "O: 79,\n"
        "P: 80,\n"
        "Q: 81,\n"
        "R: 82,\n"
        "S: 83,\n"
        "T: 84,\n"
        "U: 85,\n"
        "V: 86,\n"
        "W: 87,\n"
        "X: 88,\n"
        "Y: 89,\n"
        "Z: 90,\n"
        "LeftBracket: 91,\n"
        "Backslash: 92,\n"
        "RightBracket: 93,\n"
        "Grave: 96,\n"
        "Space: 32,\n"
        "Escape: 256,\n"
        "Enter: 257,\n"
        "Tab: 258,\n"
        "Backspace: 259,\n"
        "Insert: 260,\n"
        "Delete: 261,\n"
        "Right: 262,\n"
        "Left: 263,\n"
        "Down: 264,\n"
        "Up: 265,\n"
        "PageUp: 266,\n"
        "PageDown: 267,\n"
        "Home: 268,\n"
        "End: 269,\n"
        "CapsLock: 280,\n"
        "ScrollLock: 281,\n"
        "NumLock: 282,\n"
        "PrintScreen: 283,\n"
        "Pause: 284,\n"
        "F1: 290,\n"
        "F2: 291,\n"
        "F3: 292,\n"
        "F4: 293,\n"
        "F5: 294,\n"
        "F6: 295,\n"
        "F7: 296,\n"
        "F8: 297,\n"
        "F9: 298,\n"
        "F10: 299,\n"
        "F11: 300,\n"
        "F12: 301,\n"
        "LeftShift: 340,\n"
        "LeftControl: 341,\n"
        "LeftAlt: 342,\n"
        "LeftSuper: 343,\n"
        "RightShift: 344,\n"
        "RightControl: 345,\n"
        "RightAlt: 346,\n"
        "RightSuper: 347,\n"
        "KbMenu: 348,\n"
        "Kp0: 320,\n"
        "Kp1: 321,\n"
        "Kp2: 322,\n"
        "Kp3: 323,\n"
        "Kp4: 324,\n"
        "Kp5: 325,\n"
        "Kp6: 326,\n"
        "Kp7: 327,\n"
        "Kp8: 328,\n"
        "Kp9: 329,\n"
        "KpDecimal: 330,\n"
        "KpDivide: 331,\n"
        "KpMultiply: 332,\n"
        "KpSubtract: 333,\n"
        "KpAdd: 334,\n"
        "KpEnter: 335,\n"
        "KpEqual: 336,\n"
        "Back: 4,\n"
        "Menu: 5,\n"
        "VolumeUp: 24,\n"
        "VolumeDown: 25\n"
    "};\n"
    "var MouseButton = {\n"
        "ButtonLeft: 0,\n"
        "ButtonRight: 1,\n"
        "ButtonMiddle: 2,\n"
        "ButtonSide: 3,\n"
        "ButtonExtra: 4,\n"
        "ButtonForward: 5,\n"
        "ButtonBack: 6\n"
    "};\n"
    "var MouseCursor = {\n"
        "CursorDefault: 0,\n"
        "CursorArrow: 1,\n"
        "CursorIbeam: 2,\n"
        "CursorCrosshair: 3,\n"
        "CursorPointingHand: 4,\n"
        "CursorResizeEw: 5,\n"
        "CursorResizeNs: 6,\n"
        "CursorResizeNwse: 7,\n"
        "CursorResizeNesw: 8,\n"
        "CursorResizeAll: 9,\n"
        "CursorNotAllowed: 10\n"
    "};\n"
    "var GamepadButton = {\n"
        "ButtonUnknown: 0,\n"
        "ButtonLeftFaceUp: 1,\n"
        "ButtonLeftFaceRight: 2,\n"
        "ButtonLeftFaceDown: 3,\n"
        "ButtonLeftFaceLeft: 4,\n"
        "ButtonRightFaceUp: 5,\n"
        "ButtonRightFaceRight: 6,\n"
        "ButtonRightFaceDown: 7,\n"
        "ButtonRightFaceLeft: 8,\n"
        "ButtonLeftTrigger1: 9,\n"
        "ButtonLeftTrigger2: 10,\n"
        "ButtonRightTrigger1: 11,\n"
        "ButtonRightTrigger2: 12,\n"
        "ButtonMiddleLeft: 13,\n"
        "ButtonMiddle: 14,\n"
        "ButtonMiddleRight: 15,\n"
        "ButtonLeftThumb: 16,\n"
        "ButtonRightThumb: 17\n"
    "};\n"
    "var GamepadAxis = {\n"
        "AxisLeftX: 0,\n"
        "AxisLeftY: 1,\n"
        "AxisRightX: 2,\n"
        "AxisRightY: 3,\n"
        "AxisLeftTrigger: 4,\n"
        "AxisRightTrigger: 5\n"
    "};\n"
    "var MaterialMapIndex = {\n"
        "MapAlbedo: 0,\n"
        "MapMetalness: 1,\n"
        "MapNormal: 2,\n"
        "MapRoughness: 3,\n"
        "MapOcclusion: 4,\n"
        "MapEmission: 5,\n"
        "MapHeight: 6,\n"
        "MapCubemap: 7,\n"
        "MapIrradiance: 8,\n"
        "MapPrefilter: 9,\n"
        "MapBrdf: 10\n"
    "};\n"
    "var ShaderLocationIndex = {\n"
        "LocVertexPosition: 0,\n"
        "LocVertexTexcoord01: 1,\n"
        "LocVertexTexcoord02: 2,\n"
        "LocVertexNormal: 3,\n"
        "LocVertexTangent: 4,\n"
        "LocVertexColor: 5,\n"
        "LocMatrixMvp: 6,\n"
        "LocMatrixView: 7,\n"
        "LocMatrixProjection: 8,\n"
        "LocMatrixModel: 9,\n"
        "LocMatrixNormal: 10,\n"
        "LocVectorView: 11,\n"
        "LocColorDiffuse: 12,\n"
        "LocColorSpecular: 13,\n"
        "LocColorAmbient: 14,\n"
        "LocMapAlbedo: 15,\n"
        "LocMapMetalness: 16,\n"
        "LocMapNormal: 17,\n"
        "LocMapRoughness: 18,\n"
        "LocMapOcclusion: 19,\n"
        "LocMapEmission: 20,\n"
        "LocMapHeight: 21,\n"
        "LocMapCubemap: 22,\n"
        "LocMapIrradiance: 23,\n"
        "LocMapPrefilter: 24,\n"
        "LocMapBrdf: 25,\n"
        "LocVertexBoneids: 26,\n"
        "LocVertexBoneweights: 27,\n"
        "LocBoneMatrices: 28\n"
    "};\n"
    "var ShaderUniformDataType = {\n"
        "UniformFloat: 0,\n"
        "UniformVec2: 1,\n"
        "UniformVec3: 2,\n"
        "UniformVec4: 3,\n"
        "UniformInt: 4,\n"
        "UniformIvec2: 5,\n"
        "UniformIvec3: 6,\n"
        "UniformIvec4: 7,\n"
        "UniformSampler2d: 8\n"
    "};\n"
    "var ShaderAttributeDataType = {\n"
        "AttribFloat: 0,\n"
        "AttribVec2: 1,\n"
        "AttribVec3: 2,\n"
        "AttribVec4: 3\n"
    "};\n"
    "var PixelFormat = {\n"
        "UncompressedGrayscale: 1,\n"
        "UncompressedGrayAlpha: 2,\n"
        "UncompressedR5g6b5: 3,\n"
        "UncompressedR8g8b8: 4,\n"
        "UncompressedR5g5b5a1: 5,\n"
        "UncompressedR4g4b4a4: 6,\n"
        "UncompressedR8g8b8a8: 7,\n"
        "UncompressedR32: 8,\n"
        "UncompressedR32g32b32: 9,\n"
        "UncompressedR32g32b32a32: 10,\n"
        "UncompressedR16: 11,\n"
        "UncompressedR16g16b16: 12,\n"
        "UncompressedR16g16b16a16: 13,\n"
        "CompressedDxt1Rgb: 14,\n"
        "CompressedDxt1Rgba: 15,\n"
        "CompressedDxt3Rgba: 16,\n"
        "CompressedDxt5Rgba: 17,\n"
        "CompressedEtc1Rgb: 18,\n"
        "CompressedEtc2Rgb: 19,\n"
        "CompressedEtc2EacRgba: 20,\n"
        "CompressedPvrtRgb: 21,\n"
        "CompressedPvrtRgba: 22,\n"
        "CompressedAstc4x4Rgba: 23,\n"
        "CompressedAstc8x8Rgba: 24\n"
    "};\n"
    "var TextureFilter = {\n"
        "FilterPoint: 0,\n"
        "FilterBilinear: 1,\n"
        "FilterTrilinear: 2,\n"
        "FilterAnisotropic4x: 3,\n"
        "FilterAnisotropic8x: 4,\n"
        "FilterAnisotropic16x: 5\n"
    "};\n"
    "var TextureWrap = {\n"
        "WrapRepeat: 0,\n"
        "WrapClamp: 1,\n"
        "WrapMirrorRepeat: 2,\n"
        "WrapMirrorClamp: 3\n"
    "};\n"
    "var CubemapLayout = {\n"
        "LayoutAutoDetect: 0,\n"
        "LayoutLineVertical: 1,\n"
        "LayoutLineHorizontal: 2,\n"
        "LayoutCrossThreeByFour: 3,\n"
        "LayoutCrossFourByThree: 4\n"
    "};\n"
    "var FontType = {\n"
        "Default: 0,\n"
        "Bitmap: 1,\n"
        "Sdf: 2\n"
    "};\n"
    "var BlendMode = {\n"
        "Alpha: 0,\n"
        "Additive: 1,\n"
        "Multiplied: 2,\n"
        "AddColors: 3,\n"
        "SubtractColors: 4,\n"
        "AlphaPremultiply: 5,\n"
        "Custom: 6,\n"
        "CustomSeparate: 7\n"
    "};\n"
    "var Gesture = {\n"
        "None: 0,\n"
        "Tap: 1,\n"
        "Doubletap: 2,\n"
        "Hold: 4,\n"
        "Drag: 8,\n"
        "SwipeRight: 16,\n"
        "SwipeLeft: 32,\n"
        "SwipeUp: 64,\n"
        "SwipeDown: 128,\n"
        "PinchIn: 256,\n"
        "PinchOut: 512\n"
    "};\n"
    "var CameraMode = {\n"
        "Custom: 0,\n"
        "Free: 1,\n"
        "Orbital: 2,\n"
        "FirstPerson: 3,\n"
        "ThirdPerson: 4\n"
    "};\n"
    "var CameraProjection = {\n"
        "Perspective: 0,\n"
        "Orthographic: 1\n"
    "};\n"
    "var NPatchLayout = {\n"
        "NinePatch: 0,\n"
        "ThreePatchVertical: 1,\n"
        "ThreePatchHorizontal: 2\n"
    "};\n"
;
